config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks

  get 'tasks/new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create', as: :create

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update', as: :update

  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end
  def new
    @task = Task.new
  end
  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end
  def show
  end
  def edit
  end
  def update
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end
  def destroy
    @task.destroy
    redirect_to tasks_path(@task)
  end

private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.label :completed, "Completed" %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render "form", task: @task %>

<p>---------------</p>
<p><%= link_to 'Back to list', tasks_path %></p>

app/views/tasks/index.html.erb
<h1>Index / Home</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        <i class="far fa-check-square"></i>
        <% else %>
        <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task) %>
      <%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, destroy_path(task), method: :delete, data: {confirm: "Are you sure?"} %>
    </li>
  <% end %>

</ul>
<p>---------------</p>
<i class="fas fa-plus"></i>
<%= link_to 'Add a new task', new_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<p>---------------</p>
<p><%= link_to 'Back to list', tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1><h2><%= link_to "Edit this task", edit_path %></h2>

<p><%= @task.details %></p>

<% if @task.completed %>
  <i class="far fa-check-square"> This task is completed</i>
  <% else %>
  <i class="far fa-square"> This task is not completed yet</i>
<% end %>
<p>---------------</p>
<p><%= link_to 'Back to list', tasks_path %></p>